// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCp8kij15YFrKVceZflSobMqvfHcORWywE",
    authDomain: "farmer-eboard.firebaseapp.com",
    projectId: "farmer-eboard",
    storageBucket: "farmer-eboard.appspot.com",
    messagingSenderId: "920822005633",
    appId: "1:920822005633:web:a8e4256ba6e848232cb280",
    measurementId: "G-FK525NE4LG"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDvs1nJvAqvOgZls2eMooIvf1HEufQzpDg",
    appId: "1:920822005633:android:54b05979ddaafcee2cb280",
    messagingSenderId: "920822005633",
    projectId: "farmer-eboard",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvs1nJvAqvOgZls2eMooIvf1HEufQzpDg',
    appId: '1:920822005633:ios:2ec4f062a838c0ce2cb280',
    messagingSenderId: '920822005633',
    projectId: 'farmer-eboard',
    storageBucket: 'farmer-eboard.appspot.com',
    iosBundleId: 'com.example.farmerEboard',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: '',
  //   appId: '',
  //   messagingSenderId: '',
  //   projectId: '',
  //   storageBucket: '',
  //   iosBundleId: '',
  // );
}